### ISSUE TITLE
sidecar healthcheck prober should work without `PCAP_USE_CRON`

### ISSUE THREAD

**Issue by thomasmburke** [gchux/cloud-run-tcpdump#11]

**Comment by gchux** [comment]
https://github.com/gchux/cloud-run-tcpdump/blob/v1.0.0-rc55/tcpdumpw/main.go#L451-L459

was OK, but it also was a bug when not using `PCAP_USE_CRON`

fix: https://github.com/gchux/cloud-run-tcpdump/commit/547fcf05ac36a1d3612c86f3dfd8cded61a52cd9#diff-4d06441136b46d828eff5bedbca3ccf971543378d207d82ee1273b0c18190779R416

**Comment by gchux** [comment]
RELEASE: ghcr.io/gchux/cloud-run-tcpdump:v1.0.58

**Comment by gchux** [comment]
see: #9
