### ISSUE TITLE
add section `FEATURES` to `README`

### ISSUE THREAD

**Issue by gchux** [gchux/cloud-run-tcpdump#15]
as the sidecar has reached is MVP status, we are missing a features section should include:

- HTTP/1.1  and HTTP/2 analysis ( for all non encrypted connections, which is usually ingress traffic )
- link packets via flow id ( 5-tuple ) and trace id to analyze in Cloud Trace
- export PCAP files into GCS
- rich Cloud Logging entries
- etc...

**Comment by thomasmburke** [comment]
Completed in https://github.com/gchux/cloud-run-tcpdump/commit/4711901d93219904e88568b98832b2e7e4ffa5c5
