### ISSUE TITLE
[FR] Support for Cloud Run gen1 execution environment

### ISSUE THREAD

**Issue by thomasmburke** [gchux/cloud-run-tcpdump#18]

**Comment by gchux** [comment]
should use latest minor release of `v1.9.*`:

- https://www.tcpdump.org/release/libpcap-1.9.1.tar.gz

**Comment by gchux** [comment]
tracking implementation at `ft/run-gen1`:

https://github.com/gchux/cloud-run-tcpdump/blob/ft/run-gen1/base-image/Dockerfile

**Comment by gchux** [comment]
tests were successful using:

- libpcap v1.9.1
- tcpdump v4.99.5

![image](https://github.com/user-attachments/assets/679e4ab3-1d4e-4b27-a4ed-9c3e7e0e1ac3)

---

build pipeline also working OK, [`tcpdumpw`](https://github.com/gchux/cloud-run-tcpdump/blob/ft/run-gen1/tcpdumpw/Dockerfile) build without problems.

---

new PCAP sidecar base images available at: https://github.com/gchux/cloud-run-tcpdump/tree/ft/run-gen1/base-image

**Comment by gchux** [comment]
see commit: https://github.com/gchux/cloud-run-tcpdump/commit/e4dcdf4847b7fae8cbdd7d9ea3bbc9ee894f0d61

**Comment by gchux** [comment]
keeping the build process DRY: https://github.com/gchux/cloud-run-tcpdump/commit/3ada5fd78740c11b6f85aab9f5cdde0e395291e1

**Comment by gchux** [comment]
in general, both `libpcap` and `tcpdump` are fetched from: https://www.tcpdump.org/release/

and then a [Debian base image with the shared objects and binaries](https://github.com/gchux/cloud-run-tcpdump/blob/ft/run-gen1/base-image/Dockerfile) will be created to be used as-is or to import assets from it.

The base image is then used to create both:

- the [sidecar ubuntu:22.04 base image](https://github.com/gchux/cloud-run-tcpdump/blob/ft/run-gen1/base-image/sidecar.Dockerfile) used to [build the sidecar](https://github.com/gchux/cloud-run-tcpdump/blob/ft/run-gen1/Dockerfile#L15),
- and the [`golang` base image](https://github.com/gchux/cloud-run-tcpdump/blob/ft/run-gen1/base-image/golang.Dockerfile) used to build [`tcpdumpw`](https://github.com/gchux/cloud-run-tcpdump/blob/ft/run-gen1/tcpdumpw/Dockerfile#L17)

This approach should be simple enough to have full control over the underlying dependencies and still keep the build simple.

**Comment by gchux** [comment]
available at [ghcr.io/gchux/cloud-run-tcpdump:v1.0.62-RC1](https://github.com/gchux/cloud-run-tcpdump/pkgs/container/cloud-run-tcpdump/276566826?tag=v1.0.62-RC1)

relevant commits:
- https://github.com/gchux/cloud-run-tcpdump/commit/4a27b7aeaea5be2a3edff25bca7884b74f2d9ba4
- https://github.com/gchux/pcap-cli/commit/45d1cc241ef2cd38402e4cdddd576ea0cb07db27

**Comment by gchux** [comment]
https://github.com/gchux/pcap-cli/commit/45d1cc241ef2cd38402e4cdddd576ea0cb07db27 is of particular interest as it improves handling of `SIGTERM` by the PCAP packet transformer so that:

- if `SIGTERM` is received while any number of translations are in process, [it will drop them ( not write the into writers ) into STDERR instead](https://github.com/gchux/pcap-cli/blob/v1.0.0-rc107/pkg/transformer/transformer.go#L255-L262).
- [PCAP writers are now context aware](https://github.com/gchux/pcap-cli/blob/v1.0.0-rc107/pkg/pcap/pcap_writer.go#L191-L198), and if not `std{out|err}` those will be closed on `SIGTERM`
- prevent leaking of [`goroutine`s by translations consumers](https://github.com/gchux/pcap-cli/blob/v1.0.0-rc107/pkg/transformer/transformer.go#L550-L555) ( 1 per writer per NIC ); this is also related to `SIGTERM` handling improvements.
- In order to operate in the least blocking possible way, PCAP transformer commits to translate and write every packet delivered by the [`gopacket` engine](https://github.com/gchux/pcap-cli/blob/v1.0.0-rc107/pkg/pcap/gopacket_engine.go#L155) if the context is not done by the time [PCAP transformer received the packet](https://github.com/gchux/pcap-cli/blob/v1.0.0-rc107/pkg/transformer/transformer.go#L366); commitment here means that PCAP transformer is expected to generate 1 packet translation and to have that 1 packet translation [written into all writers](https://github.com/gchux/pcap-cli/blob/v1.0.0-rc107/pkg/transformer/transformer.go#L515-L522)
    - transformer also [waits for all translations](https://github.com/gchux/pcap-cli/blob/v1.0.0-rc107/pkg/transformer/transformer.go#L298-L307) it has committed to fulfill before it stops.
    - this commitment is disrupted by `SIGTERM`, which as mentioned may happen:
        - [while packet translations are already in progress](https://github.com/gchux/pcap-cli/blob/v1.0.0-rc107/pkg/transformer/transformer.go#L383)
        - [before the translation process is started](https://github.com/gchux/pcap-cli/blob/v1.0.0-rc107/pkg/transformer/transformer.go#L492) ( while translation workers are waiting from a gouroutine in the pool to become available )
    - this means that if the transformer has already committed to translate and write a packet before `SIGTERM` is received, it must also take care of:
        - [not starting queued translation workers if context is done](https://github.com/gchux/pcap-cli/blob/v1.0.0-rc107/pkg/transformer/transformer.go#L376-L381) before a goroutine is available; which means that it must rollback its commitment by calling done on the `sync.WaitGroup`
            - this also applies when goroutine pool operates in [FIFO mode](https://github.com/gchux/pcap-cli/blob/v1.0.0-rc107/pkg/transformer/transformer.go#L473-L484)

---

overall we should be losing close to 0 JSON packet translations captured before `SIGTERM` is trapped: either those packets will be fully dumped into their respective PCAP writers or into `STDERR`, provided that all the work is completed within `2s`.

**Comment by gchux** [comment]
@thomasmburke I think that we should define a strategy to have X amount of the PCAP sidecar flavors based on the combination of `libpcap` and `tcpdump` versions.

Maybe we can provide 2:
- bleeding edge: latest version for both dependencies.
- Cloud Run `gen1` compatible combination.

**Comment by gchux** [comment]
see: https://github.com/gchux/cloud-run-tcpdump/commit/1ab445c7e413bc112a65c136b6f1dc8a0774dfa1

---

- base image for all builders: [`pcap-base:libpcap-v${LIBPCAP_VERSION}_tcpdump-v${TCPDUMP_VERSION}`](https://github.com/gchux/cloud-run-tcpdump/blob/ft/run-gen1/base-image/base.Dockerfile)
- base image for golang builders: [`pcap-golang:libpcap-v${LIBPCAP_VERSION}_tcpdump-v${TCPDUMP_VERSION}`](https://github.com/gchux/cloud-run-tcpdump/blob/ft/run-gen1/base-image/golang.Dockerfile)
- base image for sidecar builder: [`pcap-sidecar:libpcap-v${LIBPCAP_VERSION}_tcpdump-v${TCPDUMP_VERSION}`](https://github.com/gchux/cloud-run-tcpdump/blob/ft/run-gen1/base-image/sidecar.Dockerfile)

---

**`PCAP sidecar`** now comes in to flavors: `gen1` and `gen2`

- [`ghcr.io/gchux/cloud-run-tcpdump:v1.0.62-gen1-RC1`](https://github.com/gchux/cloud-run-tcpdump/pkgs/container/cloud-run-tcpdump/278208204?tag=v1.0.62-gen1-RC1)
- [`ghcr.io/gchux/cloud-run-tcpdump:v1.0.62-gen2-RC1`](https://github.com/gchux/cloud-run-tcpdump/pkgs/container/cloud-run-tcpdump/278207143?tag=v1.0.62-gen2-RC1)

- Both `Docker` image flavors now contain labels to identify the version of `libpcap` and `tcpdump` used to build the base images.
- Build process for any flavor no longer installs `libpcap` nor `tcpdump` from `ubuntu` repos, it fetches and builds specific versions from `https://www.tcpdump.org/release/` ( this allows the `PCAP sidecar` to have an independent release track from Canonical ).
- [`docker_build`](https://github.com/gchux/cloud-run-tcpdump/blob/ft/run-gen1/docker_build) script now requires to specific [runtime environment](https://github.com/gchux/cloud-run-tcpdump/tree/ft/run-gen1/env) which allows to pin versions of `libpcap` and `tcpdump` per runtime ( i/e: Cloud Run, App Engine, Kubernetes Engine, etc... ).

**Comment by gchux** [comment]
we are now almost good to call this **FR** done.

**Comment by gchux** [comment]
no that the [docker_build](https://github.com/gchux/cloud-run-tcpdump/blob/ft/run-gen1/docker_build) required the environment to build the `PCAP sidecar` for, we need to update the [Cloud Build branch](https://github.com/gchux/cloud-run-tcpdump/blob/gcb/cloudbuild.yaml) and the [`README`](https://github.com/gchux/cloud-run-tcpdump/blob/gcb/cloudbuild.yaml)

**Comment by gchux** [comment]
images for `v1.1.0`

- Cloud Run `gen2`: [ghcr.io/gchux/cloud-run-tcpdump:v1.1.0-gen2](https://github.com/gchux/cloud-run-tcpdump/pkgs/container/cloud-run-tcpdump/279660417?tag=v1.1.0-gen2)
    - alias [ghcr.io/gchux/cloud-run-tcpdump:newest](https://github.com/gchux/cloud-run-tcpdump/pkgs/container/cloud-run-tcpdump/279660417?tag=newest)
    - contains newest versions of `libpcap` (`v1.10.5`) and `tcpdump` (`v4.99.5`)
- Cloud Run `gen1`: [ghcr.io/gchux/cloud-run-tcpdump:v1.1.0-gen1](https://github.com/gchux/cloud-run-tcpdump/pkgs/container/cloud-run-tcpdump/279660289?tag=v1.1.0-gen1)
    - alias [ghcr.io/gchux/cloud-run-tcpdump:latest](https://github.com/gchux/cloud-run-tcpdump/pkgs/container/cloud-run-tcpdump/279660289?tag=latest)
    - contains versions of `libpcap` (`v1.8.1`) and `tcpdump` (`v4.9.3`) that work with both Cloud Run `gen1` and `gen2`
