### ISSUE TITLE
[DOCS] – document `newest` tag introduced in `v1.1.0`

### ISSUE THREAD

**Issue by gchux** [gchux/cloud-run-tcpdump#20]
As of [v1.1.0](https://github.com/gchux/cloud-run-tcpdump/releases/tag/v1.1.0), we have 2 release tracks for `gen1` and `gen2`

we should proceed to document the differences between the new Docker images tags: `latest` and `newest`.

See: https://github.com/gchux/cloud-run-tcpdump/issues/18#issuecomment-2376000966

In general we now have 2 flavors: 
- `ghcr.io/gchux/cloud-run-tcpdump:v#.#.#-gen1` pointed by `latest`
- `ghcr.io/gchux/cloud-run-tcpdump:v#.#.#-gen2` pointed by `newest`

---

# UPDATES

## 1. README

[`README`](https://github.com/gchux/cloud-run-tcpdump/releases/tag/v1.1.0) should be updated to reflect the change in build process:

```sh
./docker_build ${RUNTIME_ENVIRONMENT} ${TCPDUMP_IMAGE_URI}
```

`RUNTIME_ENVIRONMENT` is one of: 
- [`cloud_run_gen1`](https://github.com/gchux/cloud-run-tcpdump/blob/main/env/cloud_run_gen1.env)
- [`cloud_run_gen2`](https://github.com/gchux/cloud-run-tcpdump/blob/main/env/cloud_run_gen2.env)

the resulting Docker image URI will be suffixed with version of all relevant dependencies:
> `${TCPDUMP_IMAGE_URI}-libpcap-v${LIBPCAP_VERSION}_tcpdump-v${TCPDUMP_VERSION}_pcapcli-v${PCAPCLI_VERSION}`

## 2. `gcb` branch

It also uses the [`docker_build`]() script in the [`cloudbuild.yaml`](https://github.com/gchux/cloud-run-tcpdump/blob/gcb/cloudbuild.yaml), so it should also be update to use `${RUNTIME_ENVIRONMENT}`

**Comment by thomasmburke** [comment]
https://github.com/gchux/cloud-run-tcpdump/commit/9b7387b553ea3ff1bb1000807e9bbe5809af9302 documents the newly available public images and support for gen1

Before closing this I'll update [`docker_build`](https://github.com/gchux/cloud-run-tcpdump/blob/main/docker_build) to support customers that would like to build the image themselves and then the corresponding README section that applies.

Approach for now would be make the 3rd arg for [`docker_build`](https://github.com/gchux/cloud-run-tcpdump/blob/main/docker_build) optional. If it is passed then tag the resultant image with both `${3}-${GEN}` and `${2}:${IMAGE_TAG}`, if not then just tag with `${2}:${IMAGE_TAG}`.

**Comment by thomasmburke** [comment]
https://github.com/gchux/cloud-run-tcpdump/commit/8b2a0ecfbd2aa54c4b41dbc442495b29a9be0b53 optional 3rd arg for [docker_build](https://github.com/gchux/cloud-run-tcpdump/blob/main/docker_build)

https://github.com/gchux/cloud-run-tcpdump/commit/bc5aae754b7b0093baa8a839988fdecdc93a9ff0 update build image manually docs

**Comment by gchux** [comment]
documenting successful tests of public image on Artifact Registry:

`us-central1-docker.pkg.dev/pcap-sidecar/pcap-sidecar/pcap-sidecar:latest`

![image](https://github.com/user-attachments/assets/7210c11e-6fe8-408e-80e5-7c68b61bbb4a)

![image](https://github.com/user-attachments/assets/6f7ca9ed-0479-4507-8c7e-8bd5455f8ae1)
