### ISSUE TITLE
[FR] – Artifact Registry tags should include versions for critical dependencies

### ISSUE THREAD

**Issue by gchux** [gchux/cloud-run-tcpdump#26]
in addition to `latest`/`newest` and `v#.#.#`

Artifact registry does not show `LABEL`s from `Dockerfile` in the image's `MANIFEST` as GitHub does:

> example: https://github.com/gchux/cloud-run-tcpdump/pkgs/container/cloud-run-tcpdump/279660289?tag=v1.1.0-gen1
>
> ![image](https://github.com/user-attachments/assets/702efcc7-53d0-45a8-be89-c47fb49cb903)

we should also add a `TAG` that shows the version of critical dependencies:
- tcpdump
- libpcap
- pcap-cli

**Comment by thomasmburke** [comment]
Done with https://github.com/gchux/cloud-run-tcpdump/commit/2b22e4cd6b29d0b9e72d9b3507add3fd910458df
