### ISSUE TITLE
RemoveGAE json writer creation failure log for Cloud Run services

### ISSUE THREAD

**Issue by thomasmburke** [gchux/cloud-run-tcpdump#8]
[`jsondump GAE json writer creation failed:`](https://github.com/gchux/cloud-run-tcpdump/blob/c6b65111129b2931e79a3cb6ba575116639be331/tcpdumpw/main.go#L324) error shouldn't be logged when sidecar is run on Cloud Run

It seems we just need to omit this log if [`gaeDisabledErr` is the `writerErr`](https://github.com/gchux/cloud-run-tcpdump/blob/c6b65111129b2931e79a3cb6ba575116639be331/tcpdumpw/main.go#L321C36-L321C50)

**Comment by gchux** [comment]
agreed, seems like the current condition is not enough:

https://github.com/gchux/cloud-run-tcpdump/blob/v1.0.0-rc55/tcpdumpw/main.go#L324-L325

the correct one should be using [isGAE](https://github.com/gchux/cloud-run-tcpdump/blob/v1.0.0-rc55/tcpdumpw/main.go#L242C2-L242C7)

so it should be something like this:

`if isGAE && writerErr != nil`

**Comment by gchux** [comment]
this one along side #7 will be addressed with release v1.0.0 when we go out of release candidate cycles.

**Comment by gchux** [comment]
fix: https://github.com/gchux/cloud-run-tcpdump/blob/bug/fix/tcpdumpw/main.go#L279-L282
