### ISSUE TITLE
docs: tcp listener on port `12345`

### ISSUE THREAD

**Issue by gchux** [gchux/cloud-run-tcpdump#9]
PCAP sidecar should be the 1st container to be started; for this to happen all containers should at least depend on the PCAP sidecar.

Cloud Run requires a container to have a startup probe to be marked as a dependency of any other.

PCAP sidecar starts a simple [TCP listener that accepts connections on port `12345` and just closes them](https://github.com/gchux/cloud-run-tcpdump/blob/v1.0.0-rc55/tcpdumpw/main.go#L451-L459).

We should document how to configure the startup probe and dependency chain to make the PCAP sidecar start before anything else.

**Comment by thomasmburke** [comment]
Looking to get a pulse on if gcloud support for healthchecks has made any progress. As it stands it will add a good amount of friction for users that want to incorporate this sidecar.

**Comment by gchux** [comment]
see: issue #11

**Comment by gchux** [comment]
This behavior is guarded by the environment variable `PCAP_HC_PORT` which can be set to any `uint16` and uses `12345` by default.

The value of `PCAP_HC_PORT` is propagated to `tcpdumpw` flag `-hc_port`.

**Comment by thomasmburke** [comment]
Addressed in https://github.com/gchux/cloud-run-tcpdump/commit/21e9c22a6772e9cd6fcbe0cd8272d29a97e64d8e

Tried to keep it as concise as possible. First deploy their service with the sidecar, then update the containers to depend on the sidecar and add a TCP startup probe to the sidecar via the console.

When gcloud support for healthchecks improves we can revisit the README to make it simpler.
